version: "3.8"

services:
  web:
    build: 
      context: '.'
      dockerfile: Dockerfile
    container_name: 'web'
    restart: 'always'
    expose:
      - 80
    env_file:
      - './.env'
    networks:
      - web_network
      - nginx_network
    volumes:
      - type: "bind"
        source: "./src/"
        target: "/src/"
      
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: 'db'
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db
    volumes:
      - seiko_postgresql:/var/lib/postgresql/data
    networks:
      - web_network


volumes:
  seiko_postgresql:
    external: true

networks:
  web_network:
    external: true
  nginx_network:
    external: true
