version: "3"

services:
  web:
    build: 
      context: '.'
      dockerfile: Dockerfile
    container_name: 'web'
    restart: 'always'
    ports:
      - '8000:8000'
    env_file:
      - './.env'
    networks:
      - web_network
      - nginx_network
    volumes:
      - ./src:/blogpy
      - src_static_volume:/src/static
      - src_media_volume:/src/media
    depends_on:
      - db


  db:
    image: postgres:latest
    container_name: 'db'
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db
    volumes:
      - seiko_postgresql:/var/lib/postgresql/data
    networks:
      - web_network



volumes:
  seiko_postgresql:
    external: true
  src_static_volume:
    external: true
  src_media_volume:
    external: true
networks:
  web_network:
    external: true
  nginx_network:
    external: true
