version: "3.8"

services:
  web:
  build: ./src
  container_name: 'web'
  restart: always
  expose:
    -8000
  env_file:
    - ./.env
  volumes:
    - static_volume:/src/static
    - media_volume:/src/media
  depends_on:
    - db

  db:
    image: postgres:alpine
    containcer_name: 'db'
    restart: always

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media

    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
