# Generated by Django 3.2.5 on 2021-11-10 23:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import extensions.upload_file_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس')),
                ('has_image', models.BooleanField(default=False, verbose_name='ایا مایل به انتشار تصویر هستید')),
                ('status', models.BooleanField(default=False, verbose_name='نمایش داده شود')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, unique=True, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3, unique=True, verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=extensions.upload_file_path.upload_file_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='آدرس')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='توضیحات')),
                ('weight', models.CharField(default=None, max_length=200, verbose_name='ون محصول')),
                ('image_1', models.ImageField(upload_to=extensions.upload_file_path.upload_file_path, verbose_name='تصویر 1')),
                ('image_2', models.ImageField(upload_to=extensions.upload_file_path.upload_file_path, verbose_name='تصویر 2')),
                ('image_3', models.ImageField(upload_to=extensions.upload_file_path.upload_file_path, verbose_name='تصویر 3')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('special_offer', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('status', models.CharField(choices=[('pub', 'منتشر شده'), ('unp', 'منتشر نشده')], max_length=3, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(blank=True, related_name='category', to='product.Category', verbose_name='دسته بندی محصولات')),
                ('color', models.ManyToManyField(blank=True, related_name='product_color', to='product.Color')),
                ('size', models.ManyToManyField(related_name='product_size', to='product.Size', verbose_name='سایز ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('images', models.FileField(upload_to=extensions.upload_file_path.upload_file_path, verbose_name='تصویر')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'تصویر دسته بندی',
                'verbose_name_plural': 'تصویر دسته بندی ها',
                'ordering': ['-id'],
            },
        ),
    ]
