# Generated by Django 3.2.5 on 2022-02-24 00:40

import ckeditor_uploader.fields
import common.extensions.upload_file_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category', verbose_name='Subcategory')),
            ],
            options={
                'verbose_name': 'blog category',
                'verbose_name_plural': 'blogs category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('image', models.ImageField(upload_to=common.extensions.upload_file_path.upload_blog_file, verbose_name='image')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publication date')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'publish')], max_length=1, verbose_name='status')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ManyToManyField(default=None, related_name='blogs', to='blog.Category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
