# Generated by Django 3.2.5 on 2022-02-24 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(default=None, related_name='favorite_products', to='product.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite product',
                'verbose_name_plural': 'Favorite products',
            },
        ),
        migrations.CreateModel(
            name='FavoriteBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs', models.ManyToManyField(related_name='favorite_blogs', to='blog.Blog')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite blog',
                'verbose_name_plural': 'Favorite blogs',
            },
        ),
    ]
