# Generated by Django 3.2.5 on 2022-02-24 01:04

import ckeditor_uploader.fields
import common.extensions.upload_file_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('status', models.BooleanField(default=False, verbose_name='to be displayed?')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='subcategory')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Products category',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, unique=True, verbose_name='color')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3, unique=True, verbose_name='size')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to=common.extensions.upload_file_path.upload_product_file, verbose_name='image')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='discount')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='description')),
                ('weight', models.CharField(default=None, max_length=80, verbose_name='Product weight')),
                ('image_1', models.ImageField(upload_to=common.extensions.upload_file_path.upload_product_file, verbose_name='image 1')),
                ('image_2', models.ImageField(upload_to=common.extensions.upload_file_path.upload_product_file, verbose_name='image 2')),
                ('image_3', models.ImageField(upload_to=common.extensions.upload_file_path.upload_product_file, verbose_name='image 3')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publication date')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('special_offer', models.BooleanField(default=False, verbose_name='special_offer')),
                ('status', models.CharField(choices=[('a', 'available'), ('u', 'unavailable')], max_length=1, verbose_name='status')),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='product.Category', verbose_name='categories')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='product.Color', verbose_name='colors')),
                ('sizes', models.ManyToManyField(blank=True, related_name='products', to='product.Size', verbose_name='Sizes')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('images', models.FileField(upload_to=common.extensions.upload_file_path.upload_product_file, verbose_name='image')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Category image',
                'verbose_name_plural': 'Category images',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('body', models.TextField(max_length=500, verbose_name='body')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['-created', '-id'],
                'unique_together': {('user', 'created')},
            },
        ),
    ]
