# Generated by Django 3.2.5 on 2021-11-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(help_text='ایمیل نباید تکراری باشد', max_length=254, unique=True, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطبین',
            },
        ),
    ]
