version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - src_static_volume:/src/static
      - src_media_volume:/src/media
    networks:
      - nginx_network

volumes:
  src_static_volume:
    external: true
  src_media_volume:
    external: true
networks:
  nginx_network:
    external: true