version: "3.8"

services:
  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - type: "bind"
        source: "../src/static/"
        target: "/src/static/"

      - type: "bind"
        source: "../src/media/"
        target: "/src/media/"

      - type: "bind"
        source: "./nginx.conf"
        target: "/etc/nginx/conf.d/default.conf"
    networks:
      - nginx_network


networks:
  nginx_network:
    external: true